/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sciencelaboratorysystem;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static sciencelaboratorysystem.DateUtil.addDays;

/**
 *
 * @author Sadiqeen
 */
public class allowborrowchemical extends javax.swing.JFrame {

    private Connection con = null;
    private ResultSet rs = null;
    private PreparedStatement pst = null;
    String sql = "";
    String chemicalID = "";
    String userID = "";
    

    
    public allowborrowchemical(String get , String getID) {
        initComponents();
        con = connect.ConnectDB();
        chemicalID = get;
        userID = getID;
        getchemical();
        borrowdate.setFormats(new String[]{"dd-MM-yyyy"});
        this.setIconImage(new ImageIcon(getClass().getResource("/sciencelaboratorysystem/mainpage/ico.png")).getImage());        
    }

    allowborrowchemical() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

  private void getchemical() {
        sql = "SELECT * FROM `chemical` WHERE `ID` = '" + chemicalID + "'";
        try {
            pst = con.prepareCall(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
              chemicalabel.setText(rs.getString("chemical"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(checkc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        consentration = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Cancel = new javax.swing.JButton();
        login = new javax.swing.JButton();
        borrowdate = new org.jdesktop.swingx.JXDatePicker();
        quantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        chemicalabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reques chemical | Science Laboratory System");
        setMinimumSize(new java.awt.Dimension(400, 420));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("CS Cheangkhan", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("วันที่ยืม");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 160, 90, 30);

        consentration.setBackground(new java.awt.Color(255, 255, 255));
        consentration.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        consentration.setForeground(new java.awt.Color(28, 35, 41));
        consentration.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(consentration);
        consentration.setBounds(130, 210, 250, 30);

        jLabel3.setFont(new java.awt.Font("CS Cheangkhan", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ความเข้มข้น");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 210, 110, 30);

        Cancel.setBackground(new java.awt.Color(193, 41, 43));
        Cancel.setFont(new java.awt.Font("CS Cheangkhan", 1, 24)); // NOI18N
        Cancel.setForeground(new java.awt.Color(255, 255, 255));
        Cancel.setText("ยกเลิก");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel);
        Cancel.setBounds(20, 320, 170, 40);

        login.setBackground(new java.awt.Color(107, 166, 16));
        login.setFont(new java.awt.Font("CS Cheangkhan", 1, 24)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("ส่งคำขอ");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(200, 320, 180, 40);
        getContentPane().add(borrowdate);
        borrowdate.setBounds(130, 160, 250, 30);

        quantity.setBackground(new java.awt.Color(255, 255, 255));
        quantity.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        quantity.setForeground(new java.awt.Color(28, 35, 41));
        quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(quantity);
        quantity.setBounds(130, 260, 250, 30);

        jLabel5.setFont(new java.awt.Font("CS Cheangkhan", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ปริมาณ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 260, 110, 30);

        jLabel4.setFont(new java.awt.Font("CS Cheangkhan", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ชื่อสาร");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 110, 110, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        chemicalabel.setBackground(new java.awt.Color(255, 255, 255));
        chemicalabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        chemicalabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(chemicalabel);
        chemicalabel.setBounds(0, 0, 250, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(130, 110, 250, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sciencelaboratorysystem/login/login.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
       int check = checkemptybox();
       if (check == 1) {
           writedata();
       }
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        mainpage sc = new mainpage();
        sc.setVisible(false);
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(allowborrowchemical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(allowborrowchemical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(allowborrowchemical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(allowborrowchemical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new allowborrowchemical().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private org.jdesktop.swingx.JXDatePicker borrowdate;
    private javax.swing.JLabel chemicalabel;
    private javax.swing.JTextField consentration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JTextField quantity;
    // End of variables declaration//GEN-END:variables

    private int checkemptybox() {
        if (consentration.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please fill consentration", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            return 0;
        } else {
            return 1;
        }
    }

    private void writedata(){
        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd",Locale.US);
        String date = dFormat.format(borrowdate.getDate());
        Date returndate = borrowdate.getDate();
        try { 
            Statement st = con.createStatement();
            st.executeUpdate("INSERT INTO `borrow_chemical`(`id`, `user_id`, `chemical_id`, "
                    + "`Consentration`, `borrow_date`, `quantity`, `status`) "
                    + "VALUES (null,'" + userID
                    + "','" + chemicalID
                    + "','" + consentration.getText()
                    + "','" + date
                    + "','" + quantity.getText()
                    + "','2')");
            JOptionPane.showMessageDialog(null,"Please wait for confirm");
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
