/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sciencelaboratorysystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sadiqeen
 */
public class editequipment extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    
    private Connection con = null;
    private ResultSet rs = null;
    private PreparedStatement pst = null;
    String sql = "";
    String ID = "";
   
    public editequipment(String recieve) {
        initComponents();
        con = connect.ConnectDB();
        ID = recieve;
        setdata();
        this.setIconImage(new ImageIcon(getClass().getResource("/sciencelaboratorysystem/mainpage/ico.png")).getImage());
    }
    
    public void setdata(){
        try {
            String brandget = "";
            String ordereddate = "";
            try {
                sql = "SELECT *  FROM `equipment` WHERE`ID` = '" + ID + "'";
                pst = con.prepareCall(sql);
                rs = pst.executeQuery();
                while (rs.next()) {
                    id.setText(rs.getString("ID"));
                    name.setText(rs.getString("Equipment"));
                    price.setText(rs.getString("price"));
                    quantity.setText(rs.getString("Quantity"));
                    ordereddate = rs.getString("Ordered");
                    brandget = rs.getString(6);
                    showbrand ();
                }
            } catch (SQLException ex) {
                Logger.getLogger(checkc.class.getName()).log(Level.SEVERE, null, ex);
            }
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date a = dateFormat.parse(ordereddate);
            datec.setDate(a);
            
            brandlist.setSelectedItem(getkeybrand(brandget));
        } catch (ParseException ex) {
            Logger.getLogger(editequipment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void showbrand () {
        String brand;
        sql = "SELECT `id`, `Brand` FROM `e_brand`";
        try {
            pst = con.prepareCall(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                brand = rs.getString("Brand");
                brandlist.addItem(brand);
            }
        } catch (SQLException ex) {
            Logger.getLogger(checkc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public String getkeybrand (String brandcheck) {
        String get = "";
        System.out.println(brandcheck);
        sql = "SELECT * FROM `e_brand` WHERE id = '" + brandcheck + "'";
        try {
            pst = con.prepareCall(sql);
            rs = pst.executeQuery();
            while (rs.next()) {                
                get = rs.getString("brand");
            }
        } catch (SQLException ex) {
            Logger.getLogger(checkc.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(get);
        return get;
    }
    
        public String getkeybrand () {
        String brandcheck = brandlist.getSelectedItem().toString();
        String get = "";
        sql = "SELECT * FROM `e_brand` WHERE brand = '" + brandcheck + "'";
        try {
            pst = con.prepareCall(sql);
            rs = pst.executeQuery();
            while (rs.next()) {                
                get = rs.getString("ID");
            }
        } catch (SQLException ex) {
            Logger.getLogger(checkc.class.getName()).log(Level.SEVERE, null, ex);
        }
        return get;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        datec = new org.jdesktop.swingx.JXDatePicker();
        brandlist = new javax.swing.JComboBox<>();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit equipment  | Science Laboratory System");
        setBackground(new java.awt.Color(28, 35, 41));
        setMaximumSize(new java.awt.Dimension(400, 440));
        setMinimumSize(new java.awt.Dimension(400, 440));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 416));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("CS Cheangkhan", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ดัชนี");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 110, 80, 30);

        id.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(id);
        id.setBounds(120, 110, 260, 30);

        quantity.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(quantity);
        quantity.setBounds(120, 270, 260, 30);

        jLabel5.setFont(new java.awt.Font("CS Cheangkhan", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ปริมาณ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 270, 90, 30);

        name.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(name);
        name.setBounds(120, 150, 260, 30);

        price.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(price);
        price.setBounds(120, 230, 260, 30);

        jLabel8.setFont(new java.awt.Font("CS Cheangkhan", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("วันที่สั่งซื้อ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 190, 80, 30);

        jLabel7.setFont(new java.awt.Font("CS Cheangkhan", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ชื่ออุปกรณ์");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 150, 80, 30);

        jLabel9.setFont(new java.awt.Font("CS Cheangkhan", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ราคา/หน่วย");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 230, 80, 30);

        jLabel6.setFont(new java.awt.Font("CS Cheangkhan", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("แบรนด์");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 310, 90, 30);

        datec.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        datec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datecActionPerformed(evt);
            }
        });
        getContentPane().add(datec);
        datec.setBounds(120, 190, 260, 30);

        brandlist.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        getContentPane().add(brandlist);
        brandlist.setBounds(120, 310, 260, 30);

        save.setBackground(new java.awt.Color(107, 166, 16));
        save.setFont(new java.awt.Font("CS Cheangkhan", 1, 24)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("บันทึก");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(210, 360, 170, 40);

        cancel.setBackground(new java.awt.Color(193, 41, 43));
        cancel.setFont(new java.awt.Font("CS Cheangkhan", 1, 24)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("ยกเลิก");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(20, 360, 170, 40);

        jLabel1.setBackground(new java.awt.Color(28, 35, 41));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sciencelaboratorysystem/login/login.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 400);

        jPanel1.setBackground(new java.awt.Color(28, 35, 41));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 390, 400, 110);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dFormat.format(datec.getDate());
        System.out.println(date);
        try {
                Statement st = con.createStatement();
                st.executeUpdate("UPDATE `equipment` SET `ID`='" + id.getText() 
                        + "',`Equipment`= '" + name.getText() +"',"
                        + "`Price`= ' " + price.getText() + " ',`Quantity`= '" + quantity.getText() + 
                        "',`brand`= ' " + getkeybrand() + "' WHERE `id` = '" + ID + "' ");
                JOptionPane.showMessageDialog(null, "Save equipment!", 
                        "Complete", JOptionPane.INFORMATION_MESSAGE);
                dispose();
        } catch (SQLException ex) {
                Logger.getLogger(addequipment.class.getName()).log(Level.SEVERE, null, ex);
                 JOptionPane.showMessageDialog(null, "Sorry! we got something"
                         + " wrong ,please contact administrator", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void datecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editequipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editequipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editequipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editequipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editequipment("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> brandlist;
    private javax.swing.JButton cancel;
    private org.jdesktop.swingx.JXDatePicker datec;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
