/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sciencelaboratorysystem;
import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sadiqeen
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    int check;

    
    public login() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/sciencelaboratorysystem/mainpage/ico.png")).getImage());
    }

    
    public int check(){
        if (id.getText().length() == 0 || password.getPassword().length == 0 ){
            JOptionPane.showMessageDialog(null, "Please check your ID or Password", 
                    "Please check!", JOptionPane.ERROR_MESSAGE);
            return 0;
            
        } else {
            return 1;
        }
    }
       
    public String hash() throws UnsupportedEncodingException{
    String generatedPassword = null;
    char[] pass = password.getPassword();
    String passString = new String(pass);
    try {
         MessageDigest md = MessageDigest.getInstance("SHA-512");
         md.update(id.getText().getBytes("UTF-8"));
         byte[] bytes = md.digest(passString.getBytes("UTF-8"));
         StringBuilder sb = new StringBuilder();
         for(int i=0; i< bytes.length ;i++){
            sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
         }
         generatedPassword = sb.toString();
        } 
       catch (NoSuchAlgorithmException e){
        e.printStackTrace();
       }
    return generatedPassword;
    }
    
    public String checkdatabase (int a) {
        String url = "jdbc:mysql://localhost:3306/sls";
        String value = "";
        Connection con;
        try {
            con = DriverManager.getConnection(url,"root","");
            String query = "SELECT * FROM user where id = '" + id.getText() + "'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
              value = rs.getString(a);
            }
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        return value;
    }
   
    
    public void call (int a) {
        if (a == 1) {
            adminpage sc = new adminpage();
            sc.setVisible(true);
        } else if (a == 2) {
            studentpage sc = new studentpage(id.getText());
            sc.setVisible(true);
        }
        dispose();
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Cancel = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Log in | Science Laboratory System");
        setMaximumSize(new java.awt.Dimension(500, 700));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("CS Cheangkhan", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("รหัสผู้ใช้");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 110, 100, 30);

        id.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        id.setForeground(new java.awt.Color(28, 35, 41));
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(id);
        id.setBounds(100, 110, 280, 30);

        jLabel3.setFont(new java.awt.Font("CS Cheangkhan", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("รหัสผ่าน");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 160, 70, 30);

        Cancel.setBackground(new java.awt.Color(193, 41, 43));
        Cancel.setFont(new java.awt.Font("CS Cheangkhan", 1, 24)); // NOI18N
        Cancel.setForeground(new java.awt.Color(255, 255, 255));
        Cancel.setText("ยกเลิก");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel);
        Cancel.setBounds(20, 210, 170, 40);

        password.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(28, 35, 41));
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(password);
        password.setBounds(100, 160, 280, 30);

        login.setBackground(new java.awt.Color(107, 166, 16));
        login.setFont(new java.awt.Font("CS Cheangkhan", 1, 24)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("เข้าสู่ระบบ");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(200, 210, 180, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sciencelaboratorysystem/login/login.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        mainpage sc = new mainpage();
        sc.setVisible(true);
        dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        String pass = new String();
        String passcheck = new String();
        String position = new String();
        int a = 0;
        check = check();
        if (check == 1) {
                try {
                    pass = hash();
                    passcheck = checkdatabase(2);
                } catch (UnsupportedEncodingException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (pass.equals(passcheck)){
                    if (checkdatabase(6).equals("1")) {
                        position = checkdatabase(3);
                        if (position.equals("Admin")) {
                            a = 1;
                        } else if (position.equals("Student")){
                            a = 2;
                        }      
                        call(a);
                    } else {
                        JOptionPane.showMessageDialog(null, "Sorry your account was banned !", 
                            "Login error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Sorry please Check your ID or Password", 
                        "Login error", JOptionPane.ERROR_MESSAGE);
                }
        }
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        mainpage sc = new mainpage();
        sc.setVisible(false);
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
